
logging.level.com.jpan.jokey.service.api.JokeApiClient: DEBUG

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        loggerLevel: full

jokeapi:
  url: https://v2.jokeapi.dev/
  config:
    safe: true
    flags:
      explicit: false
      sexist: false